# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='antprop',
        ),
        migrations.RemoveField(
            model_name='document',
            name='digicomm',
        ),
        migrations.RemoveField(
            model_name='document',
            name='mec',
        ),
        migrations.RemoveField(
            model_name='document',
            name='mp',
        ),
        migrations.RemoveField(
            model_name='document',
            name='os',
        ),
        migrations.RemoveField(
            model_name='document',
            name='satcom',
        ),
        migrations.AddField(
            model_name='document',
            name='label',
            field=models.CharField(choices=[('dc', 'Digital Communications'), ('mec', 'Micro Electronic Circuits'), ('sc', 'Sat Comm'), ('mp', 'Micro Processors'), ('ap', 'Antenna & Propogation'), ('os', 'Operating Systems')], default='dc', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(upload_to='photos/'),
        ),
    ]
